server:
  port: 9081
#  error:
#    include-message: always

spring:
  datasource:
    url: jdbc:h2:mem:competition;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    validate-on-migrate: true
    schemas: PUBLIC
  h2:
    console:
      enabled: true

logging:
  level:
    cup.online.javachamp.controller: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug