create table query
(
    id     long GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
    query  varchar(120) not null,
    query_id  numeric not null,
    table_name varchar(50) not null
);

comment on table query is 'Dynamic query for specific table';

create table single_query
(
    id     long GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
    query  varchar(120) not null,
    query_id  numeric not null
);

comment on table single_query is 'Common queries';

create table report
(
    id     long GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
    report_id  numeric not null,
    table_names varchar(255) not null
);

comment on table report is 'Report for tables';
