create table query
(
    id     long GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
    query  varchar(120) not null,
    query_id  numeric not null,
    table_name varchar(50) not null
);

comment on table query is 'Dynamic query for specific table';
